### ISSUE TITLE
Add automatic MAL udpate

### ISSUE THREAD

**Issue by Vardex** [lap00zza/9anime-Companion#13]
It will be great to have 9anime companion update mal automatically like what Essentials for KissAnime or Masterani.me is doing.

**Comment by lap00zza** [comment]
Hi @Vardex , 
Thanks for the suggestion. I will definitely try and see if this is doable. I will keep you posted about the updates here. (*Might take time since I am free only during the weekends.*)

**Comment by FunkyJustin** [comment]
There's another extension for a different anime website called " Essentials for Kissanime "
It has already implemented Automatic MAL Update, just putting this here so that you could use it as a reference.

https://chrome.google.com/webstore/detail/essentials-for-kissanime/jaicfjhjlblbkhejmkfimkafjchdnafm

**Comment by lap00zza** [comment]
@FunkyJustin I have already finished the ground work for it in the rewrite. I will add this very soon. It will be added in `1.0.0-beta.2`
