### ISSUE TITLE
External Downloader

### ISSUE THREAD

**Issue by xpassionzxc** [lap00zza/9anime-Companion#28]
Hi there, when i tried selecting external down-loader.

It brings me to this page and when i select "Make sure to read the wiki on how to set up external downloaders." it didn't have any information on how to set up external downloaders.

Image ; https://ibb.co/hqOj55

-Tried Selecting Copy To Clipboard however my IDM didnt prompt to download it.
- Also tried, copying the link to google chrome but "Error 404"  https://ibb.co/kZwhsk

Do advise! Thankyou.

**Comment by lap00zza** [comment]
Hi @xpassionzxc . External download feature is not completed. I released the previous fix (https://github.com/lap00zza/9anime-Companion/issues/27#issuecomment-308515047) because of the sudden changes to 9anime API breaking the download all function of the extension. And that had parts of the external download feature which is not fully completed.

So, I would advice against using the external option for now.

**Comment by lap00zza** [comment]
although, I can try a quick fix. If you are discord PM me `Arsenic#1019`.
