### ISSUE TITLE
G1 Server Introduced

### ISSUE THREAD

**Issue by PradipH31** [lap00zza/9anime-Companion#75]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
When can we expect the update for G1 server. Will the name of the download files for IDM be like that of Rapidvideo or as of the late F4 server?

**Comment by lap00zza** [comment]
@PradipH31 will add it very soon (2-3 days max)

**Comment by lap00zza** [comment]
You can download from G now. Find the build here: https://ci.appveyor.com/project/lap00zza/9anime-Companion/build/artifacts?branch=master ([Instructions](https://github.com/lap00zza/9anime-Companion/wiki/Running-in-Developement-Mode))

Publishing to the webstore will take some time since I need to clean up a few things. Use the appveyor build till then.
