### ISSUE TITLE
Suggestion: External Download Manager

### ISSUE THREAD

**Issue by DN17** [lap00zza/9anime-Companion#8]
Hi, I just started using your chrome extension, and I really like it a lot. Just a suggestion though, maybe you could add a download all option using external download manager such as IDM? Thank you for doing such a great work. :)

**Comment by lap00zza** [comment]
Thanks for the suggestions. I will definitely add this.

**Comment by lap00zza** [comment]
Adding support for external download managers is proving harder than I thought. I can see 2 ways of implementing this:
1. Open the **Save As** Dialog box for each file and hope that the download manger grabs this and starts downloading.
2. Fetch all the video links and present it to the user (along with a copy to clipboard button). Most download managers support batch downloads and IDM also monitors the clipboard for download links.

Any thoughts?

**Comment by yumiris** [comment]
Both methods work. FDM (and maybe IDM), when integrated with the browser, will usually take over the and handle the downloading by itself. Extensions such as DownThemAll! will integrate an option in the native "Save as" dialog for Firefox, which leaves it up to the user to download using the native download manager or DTA. A screenshot shows what I mean:

![image](https://cloud.githubusercontent.com/assets/10241434/25239638/1ffa57d4-2623-11e7-859f-dca6318fa81b.png)

Currently, your extension bypasses that dialog and instead shows up the following dialog:

![image](https://cloud.githubusercontent.com/assets/10241434/25239791/a90b8228-2623-11e7-9597-0db374184c34.png)

FDM/IDM may handle that, but DTA is left out.

From what it seems, you might want to call Firefox to open the file instead of saving it. That way, the user can choose how to open/save it.

The other alternative is a nice bonus, it'd certainly be appreciated.

**Comment by lap00zza** [comment]
As far as I know, getting the Open file dialog is impossible for a extension. Only the saveAs is available. 
https://developer.chrome.com/extensions/downloads

**Comment by pctechkid** [comment]
How about this?

The extension grabs all the download links into the clipboard and then the user can just paste them into idm or any external downloader. That is the best way and easiest I could think of.

**Comment by pctechkid** [comment]
Your 2nd option above which involves the copy to clipboard button is the best possible way. Hope to see this option so soon.

**Comment by lap00zza** [comment]
Working on it 😄 I will push the changes and merge to [develop](https://github.com/lap00zza/9anime-Companion/tree/develop) by today or tomorrow. Will update here once done.

**Comment by pctechkid** [comment]
Alright! I like how fast your response. :)

**Comment by DN17** [comment]
Agree with @pctechkid , your 2nd option is a great idea. Thanks for working so fast! :)

**Comment by lap00zza** [comment]
Please try it out once and lemme know if its working as expected.
#### Chrome
* https://www.dropbox.com/s/37t9m4stspqokyt/9anime_Companion_chrome.zip?dl=0
* https://www.dropbox.com/s/nqp4madbw88kh1r/9anime_Companion_chrome.zip.asc?dl=0

#### Firefox
* https://www.dropbox.com/s/vvxwd4dar9qgm0k/9anime_Companion_firefox.zip?dl=0
* https://www.dropbox.com/s/5u4qqnvp7098hnr/9anime_Companion_firefox.zip.asc?dl=0

Instructions for running in development mode can be found here:
https://github.com/lap00zza/9anime-Companion/wiki/Running-in-Developement-Mode

#### Note
Ideally you might only want to download the `zip` files. If you use GPG, then you can verify the zip files with the corresponding `asc` files.

**Comment by pctechkid** [comment]
Issues found:

• Auto filenames gone.
• Some files would turn out to be error/not found.

![screenshot](https://cloud.githubusercontent.com/assets/27243557/25289858/f9f79db8-26fd-11e7-99cb-b797cb576f26.png)

**Comment by lap00zza** [comment]
@pctechkid 

> • Auto filenames gone.

This should probably be fixed by adding title param to the download links. 

> • Some files would turn out to be error/not found.

I am working on resolving this issue. I am guessing this happens because IDM tries to resolve a lot of files at once and google does not like that? I am facing this issue as well. I will try to come up with a solution.

Thanks for reporting the issues.

**Comment by lap00zza** [comment]
### Update
The dropbox links as posted here:
https://github.com/lap00zza/9anime-Companion/issues/8#issuecomment-296207986

Have been updated with the changes from commit (b0bca9875d4728121efe00d44d01a763d73f9d0a)

**Comment by pctechkid** [comment]
The filename issue has been resolved as expected. Looking forward with the issue regarding some files that are returning 'error'. Thank you!

![image](https://cloud.githubusercontent.com/assets/27243557/25294800/7879efbe-2713-11e7-8481-5b1d42ddffc6.png)

**Comment by lap00zza** [comment]
Hi. I just wanted to update that I am still working on resolving the files issue. As of now, I haven't been able to find out what exactly is causing it. I will probably need some time for this one. In the meantime, if you have any ideas on how to fix this, then do post here.

**Comment by pctechkid** [comment]
Mailed you something regarding this issue. Please have a time to take a look at it.

**Comment by lap00zza** [comment]
@pctechkid got it. Thanks 😄 .

**Comment by lap00zza** [comment]
Preliminary implementation of this is done with #27 . Please follow the conversation there.
