### ISSUE TITLE
Bug Or Not

### ISSUE THREAD

**Issue by sliperhr** [lap00zza/9anime-Companion#91]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

So when i was scrolling at the movie section , i come across this banner,its this from you guys or just ads?
![untitled](https://user-images.githubusercontent.com/33209981/32882413-3c421082-caef-11e7-94c1-701bca387f17.jpg)

**Comment by lap00zza** [comment]
Its from 9anime. **9anime Companion** will **never** resort to ads (source code is public domain, feel free to verify). This is fixed in this commit 3cad0c2 but not yet pushed because tests are not complete for different browsers. A temporary fix for this is to add `^https?:\/\/([a-z0-9]+[.])*wwwpromoter\.com` in your 9anime Companion ad block filter and click on *Apply changes*

![image](https://user-images.githubusercontent.com/8621583/32882583-e341d922-cada-11e7-99b6-bca7c9aa699a.png)

![image](https://user-images.githubusercontent.com/8621583/32882624-fd1d01b4-cada-11e7-99c0-af4a5693ba0e.png)

**Comment by sliperhr** [comment]
allright ,thanks 👍

**Comment by lap00zza** [comment]
Closing this issue. If you have any more questions, please feel free to reopen.
